import Head from 'next/head'
import Container from 'react-bootstrap/Container'
import Header from '../components/Header'
import Image from 'next/image'
import style from '../styles/Index.module.scss'
export default function Home() {
  return (
    <>
      <Head>
        <title>Aprendendo Next.Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/detalhe.svg" />
      </Head>
      <Container>
        <Header />
        <div className={style.flex}>
          <div>
            <Image src="/eu.JPG" alt="Carolina Aguera" width={400} height={400} />
          </div>
          <div className={style.text}>
            <Image src="/detalhe.svg" alt="Detalhe em azul e vermelho" width={100} height={100} />
            <h1>Desenvolvedora Front End & UX/UI Designer</h1>
          </div>
        </div>
      </Container>
      <Container>
        <div className={style.experiencia}>
          <div className={style.texto}>
            <h1>EXPERIÊNCIA</h1>
          </div>
          <div className={style.portifolio}>
            <div className={style.texto2}>
              <p>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas <b> HTML, CSS e JavaScript.</b>
                Para aplicativos web como a rede social Dogs eu trabalhei no UX e UI Design do projeto.
              </p>
            </div>
            <div className={style.portifolioFilho}>
              <div>
                <h2>BikeCraft</h2>
                <p className={style.text}>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas HTML, CSS e JavaScript.
                  Para aplicativos web como a rede social Dogs.
                </p>
              </div>
              <div className={style.developer}>
                <h3>Desenvolvedora Júnior</h3>
                <div className={style.lista}>
                  <p>HTML</p>
                  <p>CSS</p>
                  <p>JavaScript</p>
                </div>
              </div>
            </div>
            <div className={style.portifolioFilho}>
              <div>
                <h2>SurfBolt</h2>
                <p className={style.text}>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas HTML, CSS e JavaScript.
                  Para aplicativos web como a rede social Dogs.
                </p>
              </div>
              <div className={style.developer}>
                <h3>Estagiário</h3>
                <div className={style.lista}>
                  <p>HTML</p>
                  <p>CSS</p>
                  <p>JavaScript</p>
                </div>
              </div>
            </div>
            <div className={style.portifolioFilho}>
              <div>
                <h2>Brafé</h2>
                <p className={style.text}>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas HTML, CSS e JavaScript.
                  Para aplicativos web como a rede social Dogs.
                </p>
              </div>
              <div className={style.developer}>
                <h3>Voluntário</h3>
                <div className={style.lista}>
                  <p>HTML</p>
                  <p>CSS</p>
                  <p>JavaScript</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Container >
      <div className={style.background}>
        <Container >
          <div className={style.formacao}>
            <div className={style.textoPreto}>
              <h1>FORMAÇÃO</h1>
            </div>
            <div className={style.formacaoGrid}>
              <div className={style.paragrafo}>
                <p>Minha mais recente experiência acadêmica está sendo a Graduação em Tecnólogo em Sistemas para Internet.
                  Antes disso foi Técnico em Informática no IFPR. 🎓
                </p>
              </div>
              <div className={style.formacoes}>
                <div>
                  <h6>TÉCNICO</h6>
                  <h4>Técnico em Informática</h4>
                  <p>IFPR</p>
                </div>
                <div>
                  <h6>TECNÓLOGO</h6>
                  <h4>Sistemas para Internet</h4>
                  <p>UniAlfa</p>
                </div>
                <div>
                  <h6>Técnico</h6>
                  <h4>Informática para Internet</h4>
                  <p>SENAC-RS</p>
                </div>
              </div>
              <div className={style.cursos}>
                <h5>Cursos Intensivos</h5>
                <div>
                  <h4>Curso de Introdução a TypeScript</h4>
                  <p>10h</p>
                </div>
                <div>
                  <h4>Curso Completo de React.JS com Next.JS</h4>
                  <p>10h</p>
                </div>
              </div>
            </div>
          </div>
        </Container >
      </div>
      <div className={style.footer}>
        <Container >
          <Image src="/detalhe.svg" alt="Detalhe em azul e vermelho" width={100} height={100} />
          <footer>
            <p className={style.paragrafoFooter}>Estou disponível para novos projetos no momento. Entre em contato comigo e marcamos uma conversa 👋</p>
            <div>
              <h4>carolaguerabr@gmail.com</h4>
              <h4> +55 21 99999-9999 </h4>
            </div>
          </footer>
          <p className={style.rodape}>Carolina Aguera. Alguns Direitos Reservados</p>
        </Container >
      </div >
    </>
  )
}
