import Head from 'next/head'
import Container from 'react-bootstrap/Container'
import Header from '../components/Header'
import Image from 'next/image'
import style from '../styles/Index.module.scss'
export default function Home() {
  return (
    <Container>
      <Head>
        <title>Aprendendo Next.Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/detalhe.svg" />
      </Head>
      <Header />
      <main>
        <div className={style.flex}>
          <div>
            <Image src="/logo.jpg" alt="TeenStreetBrasil" width={500} height={500} />
          </div>
          <div className={style.text}>
            <Image src="/detalhe.svg" alt="Detalhe em verde" width={100} height={100} />
            <h1>Desenvolvedora Front End & UX/UI Designer</h1>
          </div>
        </div>
        <div className={style.experiencia}>
          <div className={style.texto}>
            <h1>EXPERIÊNCIA</h1>
          </div>
          <div className={style.portifolio}>
            <div className={style.texto2}>
              <p>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas <b> HTML, CSS e JavaScript.</b>
                Para aplicativos web como a rede social Dogs eu trabalhei no UX e UI Design do projeto.
              </p>
            </div>
            <div className={style.portifolioFilho}>
              <div>
                <h2>BikeCraft</h2>
                <p className={style.text}>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas HTML, CSS e JavaScript.
                  Para aplicativos web como a rede social Dogs.
                </p>
              </div>
              <div className={style.developer}>
                <h3>Desenvolvedora Júnior</h3>
                <div className={style.lista}>
                  <p>HTML</p>
                  <p>CSS</p>
                  <p>JavaScript</p>
                </div>
              </div>
            </div>
            <div className={style.portifolioFilho}>
              <div>
                <h2>SurfBolt</h2>
                <p className={style.text}>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas HTML, CSS e JavaScript.
                  Para aplicativos web como a rede social Dogs.
                </p>
              </div>
              <div className={style.developer}>
                <h3>Estagiário</h3>
                <div className={style.lista}>
                  <p>HTML</p>
                  <p>CSS</p>
                  <p>JavaScript</p>
                </div>
              </div>
            </div>
            <div className={style.portifolioFilho}>
              <div>
                <h2>Brafé</h2>
                <p className={style.text}>Desenvolvo pequenos projetos como o Bikcraft utilizando apenas HTML, CSS e JavaScript.
                  Para aplicativos web como a rede social Dogs.
                </p>
              </div>
              <div className={style.developer}>
                <h3>Voluntário</h3>
                <div className={style.lista}>
                  <p>HTML</p>
                  <p>CSS</p>
                  <p>JavaScript</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Container >
  )
}
