import Head from 'next/head'
import Container from 'react-bootstrap/Container'
import Header from '../components/Header'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>

      </main>
    </Container>
  )
}
